<table>
<tr><th>Abiotic stress<th>Ontology<th>Description<th>Min<th>Max<th>Unit<th>Unit info<tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=freeze injury'>freeze injury</a><td><a href='http://www.cropontology.org/terms/CO_321:0000127/' target='_new'>CO_321:0000127</a><td>Severity of plant injury caused by low temperature; no injury= 0, maximum injury= 3.<td style=text-align:center>0
             <td style=text-align:center>3<td>0-3<td>Rating 0-3
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=spring stand'>spring stand</a><td><a href='http://www.cropontology.org/terms/CO_321:0000187/' target='_new'>CO_321:0000187</a><td>Spring assessment of winter wheat stand; no living plants= 0, full stand of living plants= 9.<td style=text-align:center>0
             <td style=text-align:center>9<td>0-9<td>Rating 0-9
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=sprouting tolerance'>sprouting tolerance</a><td><a href='http://www.cropontology.org/terms/CO_321:0000081/' target='_new'>CO_321:0000081</a><td>Tolerance of grain to sprouting within the spike; highly susceptible= 1, highly tolerant= 9.<td style=text-align:center>1
             <td style=text-align:center>9<td>1-9<td>Rating 1-9
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=winter kill damage'>winter kill damage</a><td><a href='http://www.cropontology.org/terms/CO_321:0000164/' target='_new'>CO_321:0000164</a><td>Percentage of plants that emerged two weeks after planting to survive the winter conditions as assessed when dormancy breaks; 100 - winter survival %.<td style=text-align:center>0
             <td style=text-align:center>100<td>%<td>Percent
             </tr><tr><th>Agronomic<th>Ontology<th>Description<th>Min<th>Max<th>Unit<th>Unit info<tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=aboveground biomass'>aboveground biomass</a><td><a href='http://browser.planteome.org/amigo/term/TO:0000327' target='_new'>TO:0000327</a><td>Weight of plant material cut at the soil level.<td style=text-align:center>0
             <td style=text-align:center>1000<td>g<td>Gram
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=agronomic score'>agronomic score</a><td><a href='http://www.cropontology.org/terms/CO_321:0000162/' target='_new'>CO_321:0000162</a><td>Rating of overall agronomic attributes and health of plants. Scored based on observance of factors limiting yield and rate; very poor= 1, poor= 2, fair= 3, good= 4, very good= 5.<td style=text-align:center>1
             <td style=text-align:center>5<td>1-5<td>Rating 1-5
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=basal aborted spikelets per head'>basal aborted spikelets per head</a><td><a href='http://browser.planteome.org/amigo/term/TO:0000436' target='_new'>TO:0000436</a><td>Hypoplasy and abortion in the basal spikelets. Aborted spikelets appear undeveloped and no grains are produced.<td style=text-align:center>0
             <td style=text-align:center>10<td>0-10<td>Rating 0-10
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=biomass at maturity'>biomass at maturity</a><td><a href='http://browser.planteome.org/amigo/term/TO:0000327' target='_new'>TO:0000327</a><td>Total plant weight (g dwt m-1 row) from plants cut at physiological maturity (DS87).<td style=text-align:center>0
             <td style=text-align:center>600<td>g<td>Gram
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=fertile spikelets per head'>fertile spikelets per head</a><td><td>Average count of fertile spikelets per head.<td style=text-align:center>0
             <td style=text-align:center>1000<td>spikelets per head<td>
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=forage yield'>forage yield</a><td><a href='http://browser.planteome.org/amigo/term/TO:0000388' target='_new'>TO:0000388</a><td>Above ground biomass, on dry weight basis, of plant material at heading (DS55).<td style=text-align:center>0
             <td style=text-align:center>15000<td>kg ha-1<td>Kilograms per hectare
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=grain weight'>grain weight</a><td><a href='http://browser.planteome.org/amigo/term/TO:0000396' target='_new'>TO:0000396</a><td>Grain yield (g dwt) from 1 m row cut at physiological maturity (DS87).<td style=text-align:center>0
             <td style=text-align:center>750<td>g<td>Gram
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=grain weight per head'>grain weight per head</a><td><td>Average weight of grain collected from a single spike.<td style=text-align:center>0
             <td style=text-align:center>1000<td>g<td>Gram
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=grain yield'>grain yield</a><td><a href='http://browser.planteome.org/amigo/term/TO:0000396' target='_new'>TO:0000396</a><td>Grain yield expressed in kilograms per hectare.<td style=text-align:center>0
             <td style=text-align:center>20000<td>kg ha-1<td>Kilograms per hectare
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=grain yield (main tillers)'>grain yield (main tillers)</a><td><a href='http://browser.planteome.org/amigo/term/TO:0000396' target='_new'>TO:0000396</a><td>Grain yield expressed in kilograms per hectare, measured from ten spikes on the main tillers.<td style=text-align:center>0
             <td style=text-align:center>20000<td>kg ha-1<td>Kilograms per hectare
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=harvest index'>harvest index</a><td><a href='http://browser.planteome.org/amigo/term/TO:0000128' target='_new'>TO:0000128</a><td>Proportion of useable biomass i.e. grain yield divided by aboveground biomass.<td style=text-align:center>0
             <td style=text-align:center>1<td>N/A<td>
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=lodging degree'>lodging degree</a><td><td>Degree of lodging; scale 0-9.<td style=text-align:center>0
             <td style=text-align:center>9<td>0-9<td>Rating 0-9
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=lodging incidence'>lodging incidence</a><td><a href='http://browser.planteome.org/amigo/term/TO:0000068' target='_new'>TO:0000068</a><td>Percentage of the plants in a plot that lodged.<td style=text-align:center>0
             <td style=text-align:center>100<td>%<td>Percent
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=lodging incidence Z50'>lodging incidence Z50</a><td><a href='http://browser.planteome.org/amigo/term/TO:0000068' target='_new'>TO:0000068</a><td>Percentage of the plants in a plot that lodged. Measured at the Zadok 50 growth stage i.e. when the first spikelet of inflorescence is visible.<td style=text-align:center>0
             <td style=text-align:center>100<td>%<td>Percent
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=lodging incidence Z55'>lodging incidence Z55</a><td><a href='http://browser.planteome.org/amigo/term/TO:0000068' target='_new'>TO:0000068</a><td>Percentage of the plants in a plot that lodged. Measured at the Zadok 55 growth stage i.e. when half of the inflorescence has emerged.<td style=text-align:center>0
             <td style=text-align:center>100<td>%<td>Percent
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=plant height'>plant height</a><td><a href='http://browser.planteome.org/amigo/term/TO:0000207' target='_new'>TO:0000207</a><td>Height of plant from soil surface to tip of spike excluding awns.<td style=text-align:center>0
             <td style=text-align:center>250<td>cm<td>Centimeter
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=plot grain yield'>plot grain yield</a><td><a href='http://browser.planteome.org/amigo/term/TO:0000396' target='_new'>TO:0000396</a><td>Seed weight of a combined nursery plot.<td style=text-align:center>0
             <td style=text-align:center>10000<td>g<td>Gram
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=plot shattering'>plot shattering</a><td><a href='http://browser.planteome.org/amigo/term/TO:0000473' target='_new'>TO:0000473</a><td>Percentage of heads that shattered in a plot.<td style=text-align:center>0
             <td style=text-align:center>100<td>%<td>Percent
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=single kernel weight'>single kernel weight</a><td><a href='http://browser.planteome.org/amigo/term/TO:0000589' target='_new'>TO:0000589</a><td>Grain weight using the single kernel characterization system 4100 (SKCS, Perten Instruments, Huddinge, Sweden).<td style=text-align:center>0
             <td style=text-align:center>100<td>mg<td>Milligram
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=spike number'>spike number</a><td><a href='http://browser.planteome.org/amigo/term/TO:0000027' target='_new'>TO:0000027</a><td>Number of flowering stems per given area.<td style=text-align:center>0
             <td style=text-align:center>0<td>spikes per area <td>
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=spike shattering'>spike shattering</a><td><a href='http://browser.planteome.org/amigo/term/TO:0000473' target='_new'>TO:0000473</a><td>Observation of the degree of shattering i.e. grain dehisced from spike at maturity.<td style=text-align:center>0
             <td style=text-align:center>9<td>0-9<td>Rating 0-9
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=spike weight'>spike weight</a><td><a href='http://browser.planteome.org/amigo/term/TO:0000583' target='_new'>TO:0000583</a><td>Spike weight (grain + glumes/rachis/awns) in g dwt m-1 row from plants cut at physiological maturity (DS87).<td style=text-align:center>0
             <td style=text-align:center>400<td>g<td>Gram
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=sterile spikelets per head'>sterile spikelets per head</a><td><td>Average count of sterile spikelets per head.<td style=text-align:center>0
             <td style=text-align:center>100<td>spikelets per head<td>
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=thousand kernal weight (main tillers)'>thousand kernal weight (main tillers)</a><td><a href='http://browser.planteome.org/amigo/term/TO:0000382' target='_new'>TO:0000382</a><td>Seed size estimated by weighing 1000 seeds from ten spikes on the main tillers.<td style=text-align:center>0
             <td style=text-align:center>100<td>g<td>Gram
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=thousand kernel weight'>thousand kernel weight</a><td><a href='http://browser.planteome.org/amigo/term/TO:0000382' target='_new'>TO:0000382</a><td>Seed size estimated by weighing 1000 seeds.<td style=text-align:center>0
             <td style=text-align:center>100<td>g<td>Gram
             </tr><tr><th>Biotic stress<th>Ontology<th>Description<th>Min<th>Max<th>Unit<th>Unit info<tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=15-ADON level'>15-ADON level</a><td><td>Concentration of the mycotoxin deoxynivalenol (DON) in the acetylated form 15-ADON.<td style=text-align:center>0
             <td style=text-align:center>500<td>ppm<td>Parts per million
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=3-ADON level'>3-ADON level</a><td><td>Concentration of the mycotoxin deoxynivalenol (DON) in the acetylated form 3-ADON.<td style=text-align:center>0
             <td style=text-align:center>500<td>ppm<td>Parts per million
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=30 spike seed weight'>30 spike seed weight</a><td><td>Weight of seeds from 30 wheat spikes.<td style=text-align:center>0
             <td style=text-align:center>1000<td>g<td>Gram
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=bacterial leaf streak'>bacterial leaf streak</a><td><a href='http://browser.planteome.org/amigo/term/TO:0000770' target='_new'>TO:0000770</a><td>Common name: Bacterial leaf streak.  Causal organism:  Xanthomonas translucens pv. Undulosa.  Severity rating: 0=no disease; 9=all leaf photosynthetic area lost.<td style=text-align:center>0
             <td style=text-align:center>9<td>0-9<td>Rating 0-9
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=BYDV incidence 0-9'>BYDV incidence 0-9</a><td><a href='http://browser.planteome.org/amigo/term/TO:0020067' target='_new'>TO:0020067</a><td>Visual rating of incidence; 0= no symptomatic plants; 9= 100% of plants symptomatic.  Symptoms defined as chlorosis of the upper leaves.<td style=text-align:center>0
             <td style=text-align:center>9<td>0-9<td>Rating 0-9
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=BYDV incidence season average'>BYDV incidence season average</a><td><td>The mean BYDV incidence across multiple ratings; see BYDV incidence T1, BYDV incidence T2, and BYDV incidence T3.<td style=text-align:center>0
             <td style=text-align:center>100<td>%<td>Percent
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=BYDV incidence T1'>BYDV incidence T1</a><td><td>First rating in a year with multiple ratings of BYDV incidence. See BYDV incidence season average for the mean BYDV incidence across all time points.<td style=text-align:center>0
             <td style=text-align:center>100<td>%<td>Percent
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=BYDV incidence T2'>BYDV incidence T2</a><td><td>Second rating in a year with multiple ratings of BYDV incidence. See BYDV incidence season average for the mean BYDV incidence across all time points.<td style=text-align:center>0
             <td style=text-align:center>100<td>%<td>Percent
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=BYDV incidence T3'>BYDV incidence T3</a><td><td>Third rating in a year with multiple ratings for BYDV incidence. See BYDV incidence season average for the mean BYDV incidence across all time points.<td style=text-align:center>0
             <td style=text-align:center>100<td>%<td>Percent
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=BYDV reaction type'>BYDV reaction type</a><td><a href='http://browser.planteome.org/amigo/term/TO:0020067' target='_new'>TO:0020067</a><td>Resistant= 1, susceptible= 9.<td style=text-align:center>1
             <td style=text-align:center>9<td>1-9<td>Rating 1-9
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=common bunt'>common bunt</a><td><a href='http://www.cropontology.org/terms/CO_321:0000281/' target='_new'>CO_321:0000281</a><td>Reaction to Common Bunt. GRIN data are single replicate field studies with susceptible Red Bobs check every 20 rows. Common bunt ratings related to the nearest two Red Bobs check rows.<td style=text-align:center>0
             <td style=text-align:center>110<td>%<td>Percent
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=common root rot resistance'>common root rot resistance</a><td><a href='http://browser.planteome.org/amigo/term/TO:0020059' target='_new'>TO:0020059</a><td>Causal agents: Cochliobolus sativus (Bipolaris sorokiniana).  Symptoms: browning of the root, crown and basal culm tissues.  Plants may lodge.  White spikes can appear.<td style=text-align:center>0
             <td style=text-align:center>0<td>N/A<td>
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=DON level'>DON level</a><td><a href='http://browser.planteome.org/amigo/term/TO:0000669' target='_new'>TO:0000669</a><td>Deoxynivalenol (DON) mycotoxin level.<td style=text-align:center>0
             <td style=text-align:center>200<td>ppm<td>Parts per million
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=dwarf bunt'>dwarf bunt</a><td><td>Dwarf bunt is a winter wheat disease that is caused by the fungus Tilletia controversa<td style=text-align:center>0
             <td style=text-align:center>100<td>%<td>Percent
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=FHB AUDPC'>FHB AUDPC</a><td><a href='http://browser.planteome.org/amigo/term/TO:0000663' target='_new'>TO:0000663</a><td>Fusarium head blight severity rated on at least three dates expressed as the area under the disease progress curve (AUDPC), calculated according to Buerstmayr et al. (2000).<td style=text-align:center>0
             <td style=text-align:center>1000<td>%<td>Percent
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=FHB disease index'>FHB disease index</a><td><a href='http://browser.planteome.org/amigo/term/TO:0000663' target='_new'>TO:0000663</a><td>Reaction to Fusarium head blight (scab); index calculated as the disease incidence x severity/100, where incidence= % infected spikes in the sample (non-zero spikes/total spikes evaluated x 100), and severity= % of infected spikelets per spike. Each data point is an average of spikes evaluated in the sample. For trials where the FHB disease index was calculated at multiple time points, this T3 trait holds the average FHB disease index across each time point.<td style=text-align:center>0
             <td style=text-align:center>100<td>%<td>Percent
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=FHB disease index T1'>FHB disease index T1</a><td><a href='http://browser.planteome.org/amigo/term/TO:0000663' target='_new'>TO:0000663</a><td>First assessment in a growing season. See trait FHB disease index for the full trait description.<td style=text-align:center>0
             <td style=text-align:center>100<td>%<td>Percent
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=FHB disease index T2'>FHB disease index T2</a><td><a href='http://browser.planteome.org/amigo/term/TO:0000663' target='_new'>TO:0000663</a><td>Second assessment in a growing season. See trait FHB disease index for the full trait description.<td style=text-align:center>0
             <td style=text-align:center>100<td>%<td>Percent
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=FHB disease index T3'>FHB disease index T3</a><td><a href='http://browser.planteome.org/amigo/term/TO:0000663' target='_new'>TO:0000663</a><td>Third assessment in a growing season. See trait FHB disease index for the full trait description.<td style=text-align:center>0
             <td style=text-align:center>100<td>%<td>Percent
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=FHB disease index T4'>FHB disease index T4</a><td><a href='http://browser.planteome.org/amigo/term/TO:0000663' target='_new'>TO:0000663</a><td>Fourth assessment in a growing season. See trait FHB disease index for the full trait description.<td style=text-align:center>0
             <td style=text-align:center>100<td>%<td>Percent
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=FHB disease index T5'>FHB disease index T5</a><td><a href='http://browser.planteome.org/amigo/term/TO:0000663' target='_new'>TO:0000663</a><td>Fifth assessment in a growing season. See trait FHB disease index for the full trait description.<td style=text-align:center>0
             <td style=text-align:center>100<td>%<td>Percent
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=FHB disease index T6'>FHB disease index T6</a><td><a href='http://browser.planteome.org/amigo/term/TO:0000663' target='_new'>TO:0000663</a><td>Sixth assessment in a growing season. See trait FHB disease index for the full trait description.<td style=text-align:center>0
             <td style=text-align:center>100<td>%<td>Percent
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=FHB disease index T7'>FHB disease index T7</a><td><a href='http://browser.planteome.org/amigo/term/TO:0000663' target='_new'>TO:0000663</a><td>Seventh assessment in a growing season. See trait FHB disease index for the full trait description.<td style=text-align:center>0
             <td style=text-align:center>100<td>%<td>Percent
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=FHB diseased florets'>FHB diseased florets</a><td><td>Percentage of florets infected with Fusarium head blight (FHB) following point inoculation.<td style=text-align:center>0
             <td style=text-align:center>50<td>%<td>Percent
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=FHB grain incidence'>FHB grain incidence</a><td><a href='http://www.cropontology.org/terms/CO_321:0000927/' target='_new'>CO_321:0000927</a><td>Percentage of kernels exhibiting Fusarium head blight (FHB, scab) damage caused by the agent Fusarium spp. following the Jones and Mirocha (1999) method.<td style=text-align:center>0
             <td style=text-align:center>100<td>%<td>Percent
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=FHB greenhouse severity'>FHB greenhouse severity</a><td><td>Average percent of inoculated heads infected with Fusarium head blight (FHB) in greenhouse tests.<td style=text-align:center>0
             <td style=text-align:center>100<td>%<td>Percent
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=FHB incidence'>FHB incidence</a><td><a href='http://browser.planteome.org/amigo/term/TO:0000663' target='_new'>TO:0000663</a><td>Fusarium head blight (FHB) incidence is reported as the percentage of spikes that had at least one infected kernel.<td style=text-align:center>0
             <td style=text-align:center>100<td>%<td>Percent
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=FHB ISK index'>FHB ISK index</a><td><a href='http://browser.planteome.org/amigo/term/TO:0000663' target='_new'>TO:0000663</a><td>Fusarium disease index that combines FHB incidence, FHB severity, and FHB grain (kernel) incidence (ISK); calculated as 0.3 * FHB incidence + 0.3 * FHB severity + 0.4 * FHB grain incidence.<td style=text-align:center>0
             <td style=text-align:center>100<td>%<td>Percent
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=FHB rating'>FHB rating</a><td><td>FHB rating is scored on a 0-9 basis late in grain fill (e.g. 24 days after flowering) but before senescence of the spikes is too far along to distinguish FHB-bleached spikelets from normally senesced spikelets.  It provides a visual equivalent to FHB index without the need to measure FHB incidence and FHB severity.<td style=text-align:center>0
             <td style=text-align:center>9<td>0-9<td>Rating 0-9
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=FHB reaction type'>FHB reaction type</a><td><a href='http://browser.planteome.org/amigo/term/TO:0000663' target='_new'>TO:0000663</a><td>Rating scale of 0-9 in field.<td style=text-align:center>0
             <td style=text-align:center>9<td>0-9<td>Rating 0-9
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=FHB severity'>FHB severity</a><td><a href='http://browser.planteome.org/amigo/term/TO:0000663' target='_new'>TO:0000663</a><td>Average percent of 10 heads covered with Fusarium head blight.<td style=text-align:center>0
             <td style=text-align:center>100<td>%<td>Percent
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=hessian fly damage'>hessian fly damage</a><td><a href='http://www.cropontology.org/terms/CO_321:0000088/' target='_new'>CO_321:0000088</a><td>Plant reaction (resistant/susceptible= R/S) to hessian fly (Mayetiola destructor); 0-5% S (R)= 1, 6-10% S= 2, 11-15% S= 3, 16-30% S= 4, 31-45% S= 5, 46-60% S= 6, 61-70% S= 7, 71-80% S= 8, 81-100% S= 9. See trial name for biotype.<td style=text-align:center>1
             <td style=text-align:center>9<td>1-9<td>Rating 1-9
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=hessian fly damage (biotype B)'>hessian fly damage (biotype B)</a><td><a href='http://www.cropontology.org/terms/CO_321:0000088/' target='_new'>CO_321:0000088</a><td>Plant reaction to hessian fly (Mayetiola destructor) biotype B.<td style=text-align:center>0
             <td style=text-align:center>9<td>0-9<td>Rating 0-9
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=hessian fly damage (biotype C)'>hessian fly damage (biotype C)</a><td><a href='http://www.cropontology.org/terms/CO_321:0000088/' target='_new'>CO_321:0000088</a><td>Plant reaction to hessian fly (Mayetiola destructor) biotype C.<td style=text-align:center>0
             <td style=text-align:center>9<td>0-9<td>Rating 0-9
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=hessian fly damage (biotype D)'>hessian fly damage (biotype D)</a><td><a href='http://www.cropontology.org/terms/CO_321:0000088/' target='_new'>CO_321:0000088</a><td>Plant reaction to hessian fly (Mayetiola destructor) biotype D.<td style=text-align:center>0
             <td style=text-align:center>9<td>0-9<td>Rating 0-9
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=hessian fly damage (biotype L)'>hessian fly damage (biotype L)</a><td><a href='http://www.cropontology.org/terms/CO_321:0000088/' target='_new'>CO_321:0000088</a><td>Plant reaction to hessian fly (Mayetiola destructor) biotype L.<td style=text-align:center>0
             <td style=text-align:center>9<td>0-9<td>Rating 0-9
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=hessian fly damage (biotype O)'>hessian fly damage (biotype O)</a><td><a href='http://www.cropontology.org/terms/CO_321:0000088/' target='_new'>CO_321:0000088</a><td>Plant reaction to hessian fly (Mayetiola destructor) biotype O.<td style=text-align:center>0
             <td style=text-align:center>9<td>0-9<td>Rating 0-9
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=leaf rust reaction type'>leaf rust reaction type</a><td><a href='http://browser.planteome.org/amigo/term/TO:0020057' target='_new'>TO:0020057</a><td>Causal agent: Puccinia recondita f. sp. tritici.  Symptoms: circular to slightly elliptical pustules containing masses of orange to orange-brown urediniospores on the leaf surfaces and leaf sheathes  Synonyms: brown rust<td style=text-align:center>0
             <td style=text-align:center>9<td>0-9<td>Rating 0-9
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=leaf rust reaction type seedling'>leaf rust reaction type seedling</a><td><a href='http://browser.planteome.org/amigo/term/TO:0020057' target='_new'>TO:0020057</a><td><td style=text-align:center>0
             <td style=text-align:center>0<td>Disease rating 0-4 with qualifiers<td>string
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=leaf rust reaction type seedling (CA1.2)'>leaf rust reaction type seedling (CA1.2)</a><td><a href='http://browser.planteome.org/amigo/term/TO:0020057' target='_new'>TO:0020057</a><td><td style=text-align:center>0
             <td style=text-align:center>9<td>0-9<td>Rating 0-9
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=leaf rust reaction type seedling (Field Mix)'>leaf rust reaction type seedling (Field Mix)</a><td><a href='http://browser.planteome.org/amigo/term/TO:0020057' target='_new'>TO:0020057</a><td><td style=text-align:center>0
             <td style=text-align:center>9<td>0-9<td>Rating 0-9
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=leaf rust reaction type seedling (Race 1)'>leaf rust reaction type seedling (Race 1)</a><td><a href='http://browser.planteome.org/amigo/term/TO:0020057' target='_new'>TO:0020057</a><td><td style=text-align:center>0
             <td style=text-align:center>9<td>0-9<td>Rating 0-9
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=leaf rust response'>leaf rust response</a><td><a href='http://browser.planteome.org/amigo/term/TO:0020057' target='_new'>TO:0020057</a><td><td style=text-align:center>0
             <td style=text-align:center>1<td>0-1<td>Rating 0-1
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=leaf rust severity'>leaf rust severity</a><td><a href='http://browser.planteome.org/amigo/term/TO:0020057' target='_new'>TO:0020057</a><td>Causal agent: puccinia recondita f. sp. tritici.  Symptoms: circular to slightly elliptical pustules containing masses of orange to orange-brown urediniospores on the leaf surfaces and leaf sheathes.   Synonyms: brown rust<td style=text-align:center>0
             <td style=text-align:center>100<td>%<td>Percent
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=micro test weight'>micro test weight</a><td><td>The fixed Column weight of the VSK sample that fits in a 15.7 mL copper vessel measuring 20 mm in diameter and 50 mm in height.<td style=text-align:center>0
             <td style=text-align:center>1000<td>g<td>Gram
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=nivalenol level'>nivalenol level</a><td><td>Measure of the level of the compound Nivalenol.<td style=text-align:center>0
             <td style=text-align:center>500<td>ppm<td>Parts per million
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=powdery mildew reaction type'>powdery mildew reaction type</a><td><a href='http://browser.planteome.org/amigo/term/TO:0020061' target='_new'>TO:0020061</a><td>Causal agent: Blumeria graminis f. sp. tritici.  Symptoms: first visible signs are fuzzy white to pale grey tufts of mycelia and conidia on the upper surfaces of leaves and leaf sheaths (especially on lower leaves) and sometimes on the spikes.  Older fungal tissue is yellowish grey and can be easily rubbed off.  Plant tissue becomes chlorotic or necrotic.  Spherical black cleistothecia may develop. Scoring:  0= 0 to &lt;1% leaf area affected on any leaf; 1= 1-50% leaf area affected on 4th leaf; 2= 1-5% leaf area affected on 3rd leaf; 3=5-15% leaf area affected on 3rd leaf; 4= &gt;15% leaf area affected on 3rd leaf; 5= 1-5% leaf area affected on 2nd leaf; 6= 5-15% leaf area affected on 2nd leaf; 7= &gt;15% leaf area affected on 2nd leaf; 8= 1-5% leaf area affected on flag leaf; 9= 5-15% leaf area affected on flag leaf; 10= &gt;15% leaf area affected on flag leaf<td style=text-align:center>0
             <td style=text-align:center>10<td>0-10<td>Rating 0-10
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=septoria leaf blotch severity'>septoria leaf blotch severity</a><td><a href='http://browser.planteome.org/amigo/term/TO:0020065' target='_new'>TO:0020065</a><td>Causal agent: Septoria tritici  (Mycosphaerella graminicola),  Septoria nodorum (Leptosphaeria nodorum),  Septoria avenae f. sp. triticea (Leptosphaeria avenaria f. sp. triticea).  Symptoms: initial infection sites tend to be irregular in shape, oval to elongated chlorotic spots or lesions. As these sites expand, the centers of the lesions become pale, straw colored, and slightly necrotic, often with numerous small black dots (pycnidia). The lesions of Septoria tritici blotch tend to be linear and restricted laterally, while those of Septoria nodorum blotch and Septoria avenae blotch are more lens shaped. All above ground plant parts can be affected.<td style=text-align:center>0
             <td style=text-align:center>100<td>%<td>Percent
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=spot blotch  resistance'>spot blotch  resistance</a><td><a href='http://browser.planteome.org/amigo/term/TO:0020053' target='_new'>TO:0020053</a><td>Causal agent: Cochliobolus sativus (Bipolaris sorokiniana).  Symptoms: elongated to oval shaped dark brown lesions.  Centers often lighten to dark brown or tan surrounded by an irregular dark brown ring.  Synonyms: Helminthosporium leaf blotch.<td style=text-align:center>0
             <td style=text-align:center>0<td>N/A<td>
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=stagonospora nodorum glume blotch severity'>stagonospora nodorum glume blotch severity</a><td><a href='http://www.cropontology.org/terms/CO_321:0000717/' target='_new'>CO_321:0000717</a><td>Causal agent: Stagonospora nodorum. Symptoms: initial infection sites tend to be irregular in shape, oval to elongated chlorotic spots or lens shaped lesions. As these sites expand, the centers of the lesions become pale, straw colored, and slightly necrotic, often with numerous small black dots (pycnidia). All above ground plant parts can be affected. Severity of symptoms on spikes.<td style=text-align:center>0
             <td style=text-align:center>9<td>0-9<td>Rating 0-9
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=stagonospora nodorum leaf blotch reaction type'>stagonospora nodorum leaf blotch reaction type</a><td><td>Causal agent: Stagonospora nodorum. Symptoms: initial infection sites tend to be irregular in shape, oval to elongated chlorotic spots or lens shaped lesions on leaves. As these sites expand, the centers of the lesions become pale, straw colored, and slightly necrotic, often with numerous small black dots (pycnidia). All above ground plant parts can be affected. Rated on a 0-9 scale.<td style=text-align:center>0
             <td style=text-align:center>9<td>0-9<td>Rating 0-9
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=stagonospora nodorum leaf blotch severity'>stagonospora nodorum leaf blotch severity</a><td><a href='http://www.cropontology.org/terms/CO_321:0000717/' target='_new'>CO_321:0000717</a><td>Causal agent: Stagonospora nodorum. Symptoms: initial infection sites tend to be irregular in shape, oval to elongated chlorotic spots or lens shaped lesions. As these sites expand, the centers of the lesions become pale, straw colored, and slightly necrotic, often with numerous small black dots (pycnidia). All above ground plant parts can be affected. Severity of symptoms on leaves.<td style=text-align:center>0
             <td style=text-align:center>9<td>0-9<td>Rating 0-9
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=stem rust coefficient of infection'>stem rust coefficient of infection</a><td><td>The coefficient of infection (CI) is obtained by multiplying together two separate traits: stem rust severity and stem rust infection response, which are typically recorded together.<td style=text-align:center>0
             <td style=text-align:center>100<td>0-100<td>Coefficient 0-100
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=stem rust coefficient of infection T1'>stem rust coefficient of infection T1</a><td><td>The coefficient of infection (CI) at T1 is obtained by multiplying together two separate traits: stem rust severity T1 and stem rust infection response T1, which are typically recorded together.<td style=text-align:center>0
             <td style=text-align:center>100<td>0-100<td>Coefficient 0-100
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=stem rust incidence'>stem rust incidence</a><td><td>Common Name: Stem rust, black rust  Causal agent: Puccinia graminis Pers.:Pers. f. sp. tritici Eriks. E. Henn.  Symptoms: Uredinia generally appear as oval lesions on leaf sheaths, true stem, and spike. Uredinia can appear on the leaves if other diseases have not killed them. Uredinia are brick red in color and can be seen to rupture the host epidermis, on the leaves uredinia generally penetrate to sporulate on both surfaces. Infected areas are rough to the touch.<td style=text-align:center>0
             <td style=text-align:center>100<td>%<td>Percent
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=stem rust infection response'>stem rust infection response</a><td><td>A qualitative anaylsis of the type of stem rust (Puccinia graminis f. sp. Tritici) symptoms that are exhibited. Infection responses are limited to: Resistant (R): small uredinia surrounded by chlorosis or necrosis; Moderately resistant (MR): medium sized uredinia surrounded by chlorosis or necrosis; Moderately susceptible (MS): medium-large compatible uredinia without chlorosis and necrosis, and; Susceptible (S): large, compatible uredinia without chlorosis and necrosis. The following numerical scale has been used to quantify conventional notations of infection response: R= 0.2, MR= 0.4, MS= 0.8, S= 1.0 (Yu et al. 2011). Stem rust infection response is typically recorded in conjunction with stem rust severity.<td style=text-align:center>0
             <td style=text-align:center>1<td>0-1<td>Rating 0-1
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=stem rust infection response T1'>stem rust infection response T1</a><td><td>A qualitative anaylsis of the type of stem rust (Puccinia graminis f. sp. Tritici) symptoms that are exhibited. Infection responses are limited to: Resistant (R): small uredinia surrounded by chlorosis or necrosis; Moderately resistant (MR): medium sized uredinia surrounded by chlorosis or necrosis; Moderately susceptible (MS): medium-large compatible uredinia without chlorosis and necrosis, and; Susceptible (S): large, compatible uredinia without chlorosis and necrosis. The following numerical scale has been used to quantify conventional notations of infection response: R= 0.2, MR= 0.4, MS= 0.8, S= 1.0 (Yu et al. 2011). Stem rust infection response T1 is typically recorded in conjunction with stem rust severity T1. This trait represents the first of multiple measurements of stem rust infection response made during the growing season. See related trait: stem rust infection response for additional measurements. The final measurement of stem rust infection response in a growing season is recorded under the trait: stem rust infection response.<td style=text-align:center>0
             <td style=text-align:center>1<td>0-1<td>Rating 0-1
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=stem rust infection type seedling BCCBC'>stem rust infection type seedling BCCBC</a><td><td>A qualitative analysis of the type of disease symptoms exhibited by seedlings inoculated with stem rust (Puccinia graminis f. sp. tritici) race BCCBC during greenhouse trials. The original ratings, made using the scale from Stakman et al. (1962), were converted to a 0-9 linear disease scale for analysis: 0, 1-, 1, 1+, 2-, 2 2+, 3-, 3, 3+ were coded as 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, respectively (Zhang et al, 2014).<td style=text-align:center>0
             <td style=text-align:center>9<td>0-9<td>Rating 0-9
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=stem rust infection type seedling field bulk'>stem rust infection type seedling field bulk</a><td><td>A qualitative analysis of the type of disease symptoms exhibited by seedlings inoculated with stem rust (Puccinia graminis f. sp. tritici) a bulk of stem rust races from the field during greenhouse trials. The original ratings, made using the scale from Stakman et al. (1962), were converted to a 0-9 linear disease scale for analysis: 0, 1-, 1, 1+, 2-, 2 2+, 3-, 3, 3+ were coded as 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, respectively (Zhang et al, 2014).<td style=text-align:center>0
             <td style=text-align:center>9<td>0-9<td>Rating 0-9
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=stem rust infection type seedling JRCQC'>stem rust infection type seedling JRCQC</a><td><td>A qualitative analysis of the type of disease symptoms exhibited by seedlings inoculated with stem rust (Puccinia graminis f. sp. tritici) race JRCQC during greenhouse trials. The original ratings, made using the scale from Stakman et al. (1962), were converted to a 0-9 linear disease scale for analysis: 0, 1-, 1, 1+, 2-, 2 2+, 3-, 3, 3+ were coded as 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, respectively (Zhang et al, 2014).<td style=text-align:center>0
             <td style=text-align:center>9<td>0-9<td>Rating 0-9
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=stem rust infection type seedling TRTTF'>stem rust infection type seedling TRTTF</a><td><td>A qualitative analysis of the type of disease symptoms exhibited by seedlings inoculated with stem rust (Puccinia graminis f. sp. tritici) race TRTTF during greenhouse trials. The original ratings, made using the scale from Stakman et al. (1962), were converted to a 0-9 linear disease scale for analysis: 0, 1-, 1, 1+, 2-, 2 2+, 3-, 3, 3+ were coded as 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, respectively (Zhang et al, 2014).<td style=text-align:center>0
             <td style=text-align:center>9<td>0-9<td>Rating 0-9
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=stem rust infection type seedling TTKSK'>stem rust infection type seedling TTKSK</a><td><td>A qualitative analysis of the type of disease symptoms exhibited by seedlings inoculated with stem rust (Puccinia graminis f. sp. tritici) race TTKSK during greenhouse trials. The original ratings, made using the scale from Stakman et al. (1962), were converted to a 0-9 linear disease scale for analysis: 0, 1-, 1, 1+, 2-, 2 2+, 3-, 3, 3+ were coded as 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, respectively (Zhang et al, 2014).<td style=text-align:center>0
             <td style=text-align:center>9<td>0-9<td>Rating 0-9
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=stem rust infection type seedling TTTTF'>stem rust infection type seedling TTTTF</a><td><td>A qualitative analysis of the type of disease symptoms exhibited by seedlings inoculated with stem rust (Puccinia graminis f. sp. tritici) race TTTTF during greenhouse trials. The original ratings, made using the scale from Stakman et al. (1962), were converted to a 0-9 linear disease scale for analysis: 0, 1-, 1, 1+, 2-, 2 2+, 3-, 3, 3+ were coded as 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, respectively (Zhang et al, 2014).<td style=text-align:center>0
             <td style=text-align:center>9<td>0-9<td>Rating 0-9
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=stem rust severity'>stem rust severity</a><td><td>The proportion of the area of plant tissue that is occupied by rust pustules estimated following the modified Cobb Scale (Peterson et al. 1948). Stem rust severity is typically recorded in conjunction with stem rust infection response. This trait represents the final or the only measurement of stem rust severity made during the growing season. See related trait: stem rust severity T1.<td style=text-align:center>0
             <td style=text-align:center>100<td>%<td>Percent
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=stem rust severity plot'>stem rust severity plot</a><td><td>Common Name: Stem rust, black rust  Causal agent: Puccinia graminis Pers.:Pers. f. sp. tritici Eriks. E. Henn.  Symptoms: Uredinia generally appear as oval lesions on leaf sheaths, true stem, and spike. Uredinia can appear on the leaves if other diseases have not killed them. Uredinia are brick red in color and can be seen to rupture the host epidermis, on the leaves uredinia generally penetrate to sporulate on both surfaces. Infected areas are rough to the touch. Resistant= 0, susceptible= 9.<td style=text-align:center>0
             <td style=text-align:center>9<td>0-9<td>Rating 0-9
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=stem rust severity T1'>stem rust severity T1</a><td><td>The proportion of the area of plant tissue that is occupied by rust pustules estimated following the modified Cobb Scale (Peterson et al. 1948). Stem rust severity T1 is typically recorded in conjunction with stem rust infection response T1. This trait represents the first of multiple measurements of stem rust severity made during the growing season. See related trait: stem rust severity for additional measurements. The final measurement of stem rust severity in a growing season is recorded under the trait: stem rust severity.<td style=text-align:center>0
             <td style=text-align:center>100<td>%<td>Percent
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=stripe rust reaction type'>stripe rust reaction type</a><td><a href='http://browser.planteome.org/amigo/term/TO:0020055' target='_new'>TO:0020055</a><td>Disease rating from McNeal et al. (1971): 0) Immune. No visible uredia; 1) Very resistant. Necrotic flecks; 2) Resistant. Necrotic areas without sporulation; 3-4) Resistant. Necrotic and chlorotic areas with restricted sporulation; 5-6) Moderately resistant. Moderate sporulation with necrosis and chlorosis; 7-8) Moderately susceptible. Sporulation with chlorosis; 9) Susceptible. Abundant sporulation without chlorosis. Terminal adult stage for trials with multiple adult measurements.<td style=text-align:center>0
             <td style=text-align:center>9<td>0-9<td>Rating 0-9
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=stripe rust reaction type seedling'>stripe rust reaction type seedling</a><td><a href='http://browser.planteome.org/amigo/term/TO:0020055' target='_new'>TO:0020055</a><td><td style=text-align:center>0
             <td style=text-align:center>9<td>0-9<td>Rating 0-9
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=stripe rust reaction type T1'>stripe rust reaction type T1</a><td><a href='http://browser.planteome.org/amigo/term/TO:0020055' target='_new'>TO:0020055</a><td>First rating in a field grown plant. See the experiment annotation for the specific growth stage. See adult stripe rust reaction type for full trait description.<td style=text-align:center>0
             <td style=text-align:center>9<td>0-9<td>Rating 0-9
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=stripe rust reaction type T2'>stripe rust reaction type T2</a><td><a href='http://browser.planteome.org/amigo/term/TO:0020055' target='_new'>TO:0020055</a><td>Second rating in a field grown plant. See the experiment annotation for the specific growth stage. See adult stripe rust reaction type for full trait description.<td style=text-align:center>0
             <td style=text-align:center>9<td>0-9<td>Rating 0-9
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=stripe rust reaction type T3'>stripe rust reaction type T3</a><td><a href='http://browser.planteome.org/amigo/term/TO:0020055' target='_new'>TO:0020055</a><td>Third rating in a field grown plant. see the experiment annotation for the specific growth stage. see adult stripe rust reaction type for full trait description.<td style=text-align:center>0
             <td style=text-align:center>9<td>0-9<td>Rating 0-9
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=stripe rust reaction type T4'>stripe rust reaction type T4</a><td><a href='http://browser.planteome.org/amigo/term/TO:0020055' target='_new'>TO:0020055</a><td>Fourth rating in a field grown plant. see the experiment annotation for the specific growth stage. see adult stripe rust reaction type for full trait description.<td style=text-align:center>0
             <td style=text-align:center>9<td>0-9<td>Rating 0-9
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=stripe rust severity'>stripe rust severity</a><td><a href='http://browser.planteome.org/amigo/term/TO:0020055' target='_new'>TO:0020055</a><td>Causal agent: Puccinia striiformis f. sp.. tritici.  Symptoms: pustules (spore masses) containing yellow to orange-yellow urediniospores form narrow stripes on leaves, leaf sheaths and glumes.  Terminal adult stage for trials with multiple adult measurements.<td style=text-align:center>0
             <td style=text-align:center>100<td>%<td>Percent
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=stripe rust severity seedling'>stripe rust severity seedling</a><td><a href='http://browser.planteome.org/amigo/term/TO:0020055' target='_new'>TO:0020055</a><td>Rating scale of 0-100 in field.<td style=text-align:center>0
             <td style=text-align:center>100<td>%<td>Percent
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=stripe rust severity T1'>stripe rust severity T1</a><td><a href='http://browser.planteome.org/amigo/term/TO:0020055' target='_new'>TO:0020055</a><td>First rating in a field grown plant. See the experiment annotation for the specific growth stage. See adult stripe rust severity for full trait description.<td style=text-align:center>0
             <td style=text-align:center>100<td>%<td>Percent
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=stripe rust severity T2'>stripe rust severity T2</a><td><a href='http://browser.planteome.org/amigo/term/TO:0020055' target='_new'>TO:0020055</a><td>Second rating in a field grown plant. See the experiment annotation for the specific growth stage. See adult stripe rust severity for full trait description.<td style=text-align:center>0
             <td style=text-align:center>100<td>%<td>Percent
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=stripe rust severity T3'>stripe rust severity T3</a><td><a href='http://browser.planteome.org/amigo/term/TO:0020055' target='_new'>TO:0020055</a><td>Third rating in a field grown plant. see the experiment annotation for the specific growth stage. see adult stripe rust severity for full trait description.<td style=text-align:center>0
             <td style=text-align:center>100<td>%<td>Percent
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=stripe rust severity T4'>stripe rust severity T4</a><td><a href='http://browser.planteome.org/amigo/term/TO:0020055' target='_new'>TO:0020055</a><td>Fourth rating in a field grown plant. see the experiment annotation for the specific growth stage. see adult stripe rust severity for full trait description.<td style=text-align:center>0
             <td style=text-align:center>100<td>%<td>Percent
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=visually scabby kernels'>visually scabby kernels</a><td><td>The assessment of FHB disease recorded as % VSK by taking samples of approximately 500 kernels and following the Jones and Mirocha (1999) method to determine the percent of visually scabby kernels.<td style=text-align:center>0
             <td style=text-align:center>100<td>%<td>Percent
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=WSBMV incidence'>WSBMV incidence</a><td><td>The percentage of replications that showed symptoms within a trial.<td style=text-align:center>0
             <td style=text-align:center>100<td>%<td>Percent
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=WSBMV infection coefficient'>WSBMV infection coefficient</a><td><td>Infection coefficient; 0 = disease free, 5 = severe yellowing and stunting.<td style=text-align:center>0
             <td style=text-align:center>5<td>0-5<td>Rating 0-5
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=WSBMV reaction type'>WSBMV reaction type</a><td><a href='http://browser.planteome.org/amigo/term/TO:0000148' target='_new'>TO:0000148</a><td>Reaction to wheat soil-borne mosaic virus (WSBMV, vectored by polymyxa graminis); resistant= 0, susceptible= 9.<td style=text-align:center>0
             <td style=text-align:center>9<td>0-9<td>Rating 0-9
             </tr><tr><th>Morphological<th>Ontology<th>Description<th>Min<th>Max<th>Unit<th>Unit info<tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=chaff color'>chaff color</a><td><a href='http://browser.planteome.org/amigo/term/TO:0000221' target='_new'>TO:0000221</a><td>Chaff color at harvest.<td style=text-align:center>0
             <td style=text-align:center>0<td>N/A<td>
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=flag leaf angle'>flag leaf angle</a><td><a href='http://browser.planteome.org/amigo/term/TO:0000124' target='_new'>TO:0000124</a><td>Flag leaf angle is scored based on the visual estimate of flag leaf angle at Zadock scale 50 (inflorescence emergence). Leaf angle score: 1=100% flag leaves full upright. 9=100% flag leaves very lax<td style=text-align:center>1
             <td style=text-align:center>9<td>1-9<td>Rating 1-9
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=flag leaf angle T1'>flag leaf angle T1</a><td><a href='http://browser.planteome.org/amigo/term/TO:0000124' target='_new'>TO:0000124</a><td>Flag leaf angle is scored based on the visual estimate of flag leaf angle at Zadock scale 50 (inflorescence emergence). Leaf angle score: 1=100% flag leaves full upright. 9=100% flag leaves very lax.  A flag leaf angle \'T1\' value was taken prior to Z50.<td style=text-align:center>1
             <td style=text-align:center>9<td>1-9<td>Rating 1-9
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=flag leaf glaucousness'>flag leaf glaucousness</a><td><a href='http://www.cropontology.org/terms/CO_321:0000048/' target='_new'>CO_321:0000048</a><td>Assessment of glaucousness in flag leaf i.e. visual manifestation of epicuticular wax; no glaucousness= 0, fully covered= 10.<td style=text-align:center>0
             <td style=text-align:center>10<td>0-10<td>Rating 0-10
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=flag leaf length'>flag leaf length</a><td><a href='http://browser.planteome.org/amigo/term/TO:0002757' target='_new'>TO:0002757</a><td>Length of flag leaf (cm) from the base of the ligule to the leaf tip.<td style=text-align:center>0
             <td style=text-align:center>50<td>cm<td>Centimeter
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=flag leaf width'>flag leaf width</a><td><a href='http://browser.planteome.org/amigo/term/TO:0002758' target='_new'>TO:0002758</a><td>Width of flag leaf (cm) at the widest part of the leaf.<td style=text-align:center>0
             <td style=text-align:center>10<td>cm<td>Centimeter
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=glume pubescence'>glume pubescence</a><td><a href='http://browser.planteome.org/amigo/term/TO:0020036' target='_new'>TO:0020036</a><td>Glume hairiness or glume pubescence refers to the presence of fine hairs on the external face of the glumes and scored as absence/presence (0/1).<td style=text-align:center>0
             <td style=text-align:center>1<td>Absence/Presence<td>
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=grain number'>grain number</a><td><a href='http://browser.planteome.org/amigo/term/TO:0002759' target='_new'>TO:0002759</a><td>Grain number counted from 10 spikes of the main tillers<td style=text-align:center>0
             <td style=text-align:center>1000<td>N/A<td>
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=grain number per spikelet'>grain number per spikelet</a><td><a href='http://browser.planteome.org/amigo/term/TO:0000447' target='_new'>TO:0000447</a><td>Average grain number per fertile spikelet<td style=text-align:center>0
             <td style=text-align:center>5<td>N/A<td>
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=grain width'>grain width</a><td><a href='http://browser.planteome.org/amigo/term/TO:0000149' target='_new'>TO:0000149</a><td>Grain width analysis using the single kernel characterization system 4100 (SKCS, Perten Instruments, Huddinge, Sweden)<td style=text-align:center>0
             <td style=text-align:center>50<td>mm<td>Millimeters
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=growth habit'>growth habit</a><td><a href='http://browser.planteome.org/amigo/term/TO:0002756' target='_new'>TO:0002756</a><td>Measurement of growth habit prior to jointing on a scale of 1-4 (1=erect, 4=prostrate).<td style=text-align:center>1
             <td style=text-align:center>4<td>1-4<td>Rating 1-4
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=head wax'>head wax</a><td><td>Presence or absence of wax on the head; wax absent= 0, wax present= 1.<td style=text-align:center>0
             <td style=text-align:center>1<td>N/A<td>
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=peduncle glaucousness'>peduncle glaucousness</a><td><a href='http://www.cropontology.org/terms/CO_321:0000054/' target='_new'>CO_321:0000054</a><td>Assessment of glaucousness in peduncle i.e. visual manifestation of epicuticular wax; no glaucousness= 0, fully covered= 4.<td style=text-align:center>0
             <td style=text-align:center>4<td>0-4<td>Rating 0-4
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=peduncle length'>peduncle length</a><td><a href='http://browser.planteome.org/amigo/term/TO:0002691' target='_new'>TO:0002691</a><td>length of the region between the spike base and flag leaf<td style=text-align:center>0
             <td style=text-align:center>0<td>cm<td>Centimeter
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=pseudo-black chaff'>pseudo-black chaff</a><td><a href='http://browser.planteome.org/amigo/term/TO:0000221' target='_new'>TO:0000221</a><td>Pseudo-black chaff or melanism False black chaff is a physiological condition resulting from a deposition of melaniod pigments and is completely associated with the presence of the stem rust resistance gene Sr2. Symptoms include brown to black discoloration of the glume extending from slight longitudinal marks to large black areas covering most of the glume surface. In severe expression, the stem area below the last node may become distinctly brown to black discoloured. The trait appears post-flowering with a peak at late milk-soft dough stage.  Scoring was carried out as presence / absence (1/0)<td style=text-align:center>0
             <td style=text-align:center>1<td>Absence/Presence<td>
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=rachis length'>rachis length</a><td><td>length in mm between rachis internodes taken among 10 internodes in the center 1/3 of spike. average of 5 spikes.<td style=text-align:center>0
             <td style=text-align:center>10<td>mm<td>Millimeters
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=seed color'>seed color</a><td><a href='http://browser.planteome.org/amigo/term/TO:0000486' target='_new'>TO:0000486</a><td>Seed color at harvest.<td style=text-align:center>0
             <td style=text-align:center>0<td>N/A<td>
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=seeds per head'>seeds per head</a><td><a href='http://browser.planteome.org/amigo/term/TO:0002759' target='_new'>TO:0002759</a><td>Seeds per head determined after threshing a minimum of five harvested heads per plot.<td style=text-align:center>0
             <td style=text-align:center>100<td>Kernels per spike<td>Number of kernels per spike
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=spike color'>spike color</a><td><td>Visual rating of spike color during grain filling; 1=yellow/green to 5=blue<td style=text-align:center>1
             <td style=text-align:center>5<td>1-5<td>Rating 1-5
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=spike length'>spike length</a><td><a href='http://browser.planteome.org/amigo/term/TO:0000431' target='_new'>TO:0000431</a><td>Length of the spike at maturity<td style=text-align:center>0
             <td style=text-align:center>30<td>cm<td>Centimeter
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=spikelets per head'>spikelets per head</a><td><a href='http://browser.planteome.org/amigo/term/TO:0000456' target='_new'>TO:0000456</a><td>Number of spikelets per grain head determined from 5 random heads per plot before harvest.<td style=text-align:center>0
             <td style=text-align:center>100<td>spikelets per head<td>
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=stem diameter'>stem diameter</a><td><a href='http://browser.planteome.org/amigo/term/TO:0020083' target='_new'>TO:0020083</a><td>Stem diameter estimated on a 1-9 scale from very thin (1) to maximal thickness (9)<td style=text-align:center>1
             <td style=text-align:center>9<td>1-9<td>Rating 1-9
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=stem solidness'>stem solidness</a><td><a href='http://www.cropontology.org/terms/CO_321:0000061/' target='_new'>CO_321:0000061</a><td>Stem solidness; hollow stem= 1, solid stem= 5. The sum of the 1-5 score from five stems in a plot.<td style=text-align:center>4
             <td style=text-align:center>25<td>solidness rating 5-25<td>stem solidness value
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=waxiness'>waxiness</a><td><a href='http://browser.planteome.org/amigo/term/TO:0000709' target='_new'>TO:0000709</a><td>Waxiness is scored based on the visual estimate of the intensity of the cuticular wax deposits on the flag leaves, leaf sheaths, peduncles and spikes.  1 = absent; 2 to 5 = sparse to medium; 6 to 8 = dense; 9 = very dense<td style=text-align:center>1
             <td style=text-align:center>9<td>1-9<td>Rating 1-9
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=waxiness (spikes)'>waxiness (spikes)</a><td><a href='http://browser.planteome.org/amigo/term/TO:0000787' target='_new'>TO:0000787</a><td>Waxiness is scored based on the visual estimate of the intensity of the cuticular wax deposits on the spikes. 1 = absent; 2 to 5 = sparse to medium; 6 to 8 = dense; 9 = very dense<td style=text-align:center>1
             <td style=text-align:center>9<td>1-9<td>Rating 1-9
             </tr><tr><th>Phenological<th>Ontology<th>Description<th>Min<th>Max<th>Unit<th>Unit info<tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=days to flag leaf senescence'>days to flag leaf senescence</a><td><a href='http://browser.planteome.org/amigo/term/TO:0000249' target='_new'>TO:0000249</a><td>Number of days required for 50% of the flag leaves to lose green color.<td style=text-align:center>0
             <td style=text-align:center>250<td>days<td>Number of days
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=days to heading'>days to heading</a><td><a href='http://browser.planteome.org/amigo/term/TO:0000137' target='_new'>TO:0000137</a><td>Number of days required for 50% of the heads to emerge completely from the boot (DS55). Note: This trait has been phased out and replaced with heading date (Julian).<td style=text-align:center>0
             <td style=text-align:center>365<td>days<td>Number of days
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=days to heading (fall planting)'>days to heading (fall planting)</a><td><a href='http://browser.planteome.org/amigo/term/TO:0000137' target='_new'>TO:0000137</a><td>Number of days required for 50% of the heads to emerge completely from the boot (DS55) for fall planting of a winter crop.<td style=text-align:center>0
             <td style=text-align:center>299<td>days<td>Number of days
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=days to heading (spring planting)'>days to heading (spring planting)</a><td><a href='http://browser.planteome.org/amigo/term/TO:0000137' target='_new'>TO:0000137</a><td>Number of days required for 50% of the heads to emerge completely from the boot (DS55) for spring planting of a winter crop.<td style=text-align:center>0
             <td style=text-align:center>250<td>days<td>Number of days
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=flag leaf stay-green period'>flag leaf stay-green period</a><td><a href='http://browser.planteome.org/amigo/term/TO:0000249' target='_new'>TO:0000249</a><td>Number of days between heading and flag leaf senescence (= flag leaf senescence - days to heading).<td style=text-align:center>0
             <td style=text-align:center>100<td>days<td>Number of days
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=flowering date'>flowering date</a><td><a href='http://browser.planteome.org/amigo/term/TO:0000344' target='_new'>TO:0000344</a><td>Julian calendar date of anthesis (DS65) of approximately 50% of spikes i.e. spikes with at least 1 dehisced anther.<td style=text-align:center>0
             <td style=text-align:center>250<td>Julian date<td>Julian calendar date i.e. Jan 1= 1; Dec 31= 365(6)
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=flowering date (fall planting)'>flowering date (fall planting)</a><td><a href='http://browser.planteome.org/amigo/term/TO:0000344' target='_new'>TO:0000344</a><td>Number of days from sowing to when 50% of spikes have flowered (DS65) for fall planting of a winter crop.<td style=text-align:center>0
             <td style=text-align:center>365<td>days<td>Number of days
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=grain fill duration'>grain fill duration</a><td><a href='http://browser.planteome.org/amigo/term/TO:0000469' target='_new'>TO:0000469</a><td>Number of days from anthesis (DS65) to physiological maturity (DS87).<td style=text-align:center>0
             <td style=text-align:center>100<td>days<td>Number of days
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=heading date'>heading date</a><td><a href='http://browser.planteome.org/amigo/term/TO:0000137' target='_new'>TO:0000137</a><td>Julian calendar date of heading (DS55) i.e. when half of the inflorescence has emerged from the boot of approximately 50% of spikes in a plot.<td style=text-align:center>0
             <td style=text-align:center>365<td>Julian date<td>Julian calendar date i.e. Jan 1= 1; Dec 31= 365(6)
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=maturity date (canopy)'>maturity date (canopy)</a><td><a href='http://browser.planteome.org/amigo/term/TO:0000469' target='_new'>TO:0000469</a><td>Julian calendar date of canopy maturity i.e. when 50% of the green canopy completely loses color.<td style=text-align:center>0
             <td style=text-align:center>250<td>Julian date<td>Julian calendar date i.e. Jan 1= 1; Dec 31= 365(6)
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=maturity date (physiological)'>maturity date (physiological)</a><td><a href='http://browser.planteome.org/amigo/term/TO:0000469' target='_new'>TO:0000469</a><td>Julian calendar date of physiological maturity i.e. when 50% of the peduncles completely lose color.<td style=text-align:center>0
             <td style=text-align:center>250<td>Julian date<td>Julian calendar date i.e. Jan 1= 1; Dec 31= 365(6)
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=maturity date (spikes)'>maturity date (spikes)</a><td><a href='http://browser.planteome.org/amigo/term/TO:0000469' target='_new'>TO:0000469</a><td>Julian calendar date of spike maturity i.e. when 50% of the spikes completely lose color.<td style=text-align:center>0
             <td style=text-align:center>250<td>Julian date<td>Julian calendar date i.e. Jan 1= 1; Dec 31= 365(6)
             </tr><tr><th>Physiological<th>Ontology<th>Description<th>Min<th>Max<th>Unit<th>Unit info<tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=canopy senescence score T1'>canopy senescence score T1</a><td><a href='http://browser.planteome.org/amigo/term/TO:0000249' target='_new'>TO:0000249</a><td>Canopy senescence i.e. percentage (%) of leaf area (canopy) that has lost green color during the process of physiological maturity. T1 is the first of many observations in a season.<td style=text-align:center>0
             <td style=text-align:center>100<td>%<td>Percent
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=canopy senescence score T2'>canopy senescence score T2</a><td><a href='http://browser.planteome.org/amigo/term/TO:0000249' target='_new'>TO:0000249</a><td>Canopy senescence i.e. percentage (%) of leaf area (canopy) that has lost green color during the process of physiological maturity. T2 is the second of many observations in a season.<td style=text-align:center>0
             <td style=text-align:center>100<td>%<td>Percent
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=canopy senescence score T3'>canopy senescence score T3</a><td><a href='http://browser.planteome.org/amigo/term/TO:0000249' target='_new'>TO:0000249</a><td>Canopy senescence i.e. percentage (%) of leaf area (canopy) that has lost green color during the process of physiological maturity. T3 is the third of many observations in a season.<td style=text-align:center>0
             <td style=text-align:center>100<td>%<td>Percent
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=canopy senescence score T4'>canopy senescence score T4</a><td><a href='http://browser.planteome.org/amigo/term/TO:0000249' target='_new'>TO:0000249</a><td>Canopy senescence i.e. percentage (%) of leaf area (canopy) that has lost green color during the process of physiological maturity. T4 is the fourth of many observations in a season.<td style=text-align:center>0
             <td style=text-align:center>100<td>%<td>Percent
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=canopy senescence score T5'>canopy senescence score T5</a><td><a href='http://browser.planteome.org/amigo/term/TO:0000249' target='_new'>TO:0000249</a><td>Canopy senescence i.e. percentage (%) of leaf area (canopy) that has lost green color during the process of physiological maturity. T5 is the fifth of many observations in a season.<td style=text-align:center>0
             <td style=text-align:center>100<td>%<td>Percent
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=canopy senescence score T6'>canopy senescence score T6</a><td><a href='http://browser.planteome.org/amigo/term/TO:0000249' target='_new'>TO:0000249</a><td>Canopy senescence i.e. percentage (%) of leaf area (canopy) that has lost green color during the process of physiological maturity.T6 is the sixth of many observations in a season.<td style=text-align:center>0
             <td style=text-align:center>100<td>%<td>Percent
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=canopy senescence score T7'>canopy senescence score T7</a><td><a href='http://browser.planteome.org/amigo/term/TO:0000249' target='_new'>TO:0000249</a><td>Canopy senescence i.e. percentage (%) of leaf area (canopy) that has lost green color during the process of physiological maturity. T7 is the seventh of many observations in a season.<td style=text-align:center>0
             <td style=text-align:center>100<td>%<td>Percent
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=canopy temperature (flowering)'>canopy temperature (flowering)</a><td><a href='http://www.cropontology.org/terms/CO_321:0000193/' target='_new'>CO_321:0000193</a><td>Canopy temperature at anthesis (Feekes 10.5.1-10.5.3) measured using a hand-held infrared thermometer. The surface temperature of the canopy is related to the amount of transpiration due to evaporative cooling. See related triat: canopy temperature (grain fill).<td style=text-align:center>0
             <td style=text-align:center>50<td>&deg;C<td>Celsius
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=canopy temperature (grain fill)'>canopy temperature (grain fill)</a><td><a href='http://www.cropontology.org/terms/CO_321:0000193/' target='_new'>CO_321:0000193</a><td>Canopy temperature at grain fill (Feekes 11.1-11.2 ) measured using a hand-held infrared thermometer. The surface temperature of the canopy is related to the amount of transpiration due to evaporative cooling. See related trait: canopy temperature (flowering).<td style=text-align:center>0
             <td style=text-align:center>50<td>&deg;C<td>Celsius
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=canopy temperature depression (flowering)'>canopy temperature depression (flowering)</a><td><a href='http://www.cropontology.org/terms/CO_321:0000006/' target='_new'>CO_321:0000006</a><td>Canopy temperature depression at anthesis. Canopy temperature depression (CTD) is the difference between the ambient air temperature (Ta) and the canopy temperature (Tc): CTD=Ta-Tc.<td style=text-align:center>-100
             <td style=text-align:center>100<td>&deg;C<td>Celsius
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=canopy temperature depression (grain fill)'>canopy temperature depression (grain fill)</a><td><a href='http://www.cropontology.org/terms/CO_321:0000006/' target='_new'>CO_321:0000006</a><td>Canopy temperature depression at grain fill. Canopy temperature depression (CTD) is the difference between the ambient air temperature (Ta) and the canopy temperature (Tc): CTD=Ta-Tc.<td style=text-align:center>-100
             <td style=text-align:center>100<td>&deg;C<td>Celsius
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=flag leaf chlorophyll content'>flag leaf chlorophyll content</a><td><a href='http://browser.planteome.org/amigo/term/TO:0000495' target='_new'>TO:0000495</a><td>Chlorophyll content of the flag leaf measured by a SPAD (Special Products Analysis Division of Minolta) meter. A SPAD unit is not directly related to optical transmission through a leaf. This trait represents the final or the only measurement of flag leaf chlorophyll content in the growing season. See related traits: flag leaf chlorophyll content T1 and flag leaf chlorophyll content T2.<td style=text-align:center>0
             <td style=text-align:center>100<td>spad<td>
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=flag leaf chlorophyll content T1'>flag leaf chlorophyll content T1</a><td><a href='http://browser.planteome.org/amigo/term/TO:0000495' target='_new'>TO:0000495</a><td>Chlorophyll content of the flag leaf measured by a SPAD (Special Products Analysis Division of Minolta) meter. A SPAD unit is not directly related to optical transmission through a leaf. This trait represents the first of multiple measurements of flag leaf chlorophyll content in a growing season. See related traits: flag leaf chlorophyll content T2 and flag leaf chlorophyll content for additional measurements. The final measurement of flag leaf chlorophyll content during a growing season will be recorded under the trait: flag leaf chlorophyll content.<td style=text-align:center>0
             <td style=text-align:center>100<td>spad<td>
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=flag leaf chlorophyll content T2'>flag leaf chlorophyll content T2</a><td><a href='http://browser.planteome.org/amigo/term/TO:0000495' target='_new'>TO:0000495</a><td>Chlorophyll content of the flag leaf measured by a SPAD (Special Products Analysis Division of Minolta) meter. A SPAD unit is not directly related to optical transmission through a leaf. This trait represents the second of three measurements of flag leaf chlorophyll content in a growing season. See related traits: flag leaf chlorophyll content T1 and flag leaf chlorophyll content for the first and final measurements of flag leaf chlorophyll content respectively.<td style=text-align:center>0
             <td style=text-align:center>100<td>spad<td>
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=flag leaf senescence score'>flag leaf senescence score</a><td><a href='http://browser.planteome.org/amigo/term/TO:0000249' target='_new'>TO:0000249</a><td>Assessment of the extent of flag leaf senescence i.e. the progressive yellowing of the flag leaf. This trait represents the final or the only assessment of flag leaf senescence in a growing season. See related traits: flag leaf senescence score T1, and flag leaf senescence score T2.<td style=text-align:center>0
             <td style=text-align:center>9<td>0-9<td>Rating 0-9
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=flag leaf senescence score T1'>flag leaf senescence score T1</a><td><a href='http://browser.planteome.org/amigo/term/TO:0000249' target='_new'>TO:0000249</a><td>Assessment of the extent of flag leaf senescence i.e. the progressive yellowing of the flag leaf. This trait represents the first of multiple assessments of flag leaf senescence in a growing season. See related traits: flag leaf senescence score, and flag leaf senescence score T2 for additional assessments. The final assessment of flag leaf senescence during a growing season will be recorded under the trait: flag leaf senescence score.<td style=text-align:center>0
             <td style=text-align:center>9<td>0-9<td>Rating 0-9
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=flag leaf senescence score T2'>flag leaf senescence score T2</a><td><a href='http://browser.planteome.org/amigo/term/TO:0000249' target='_new'>TO:0000249</a><td>Assessment of the extent of flag leaf senescence i.e. the progressive yellowing of the flag leaf. This trait represents the second of three assessments of flag leaf senescence in a growing season. See related traits: flag leaf senescence score T1, flag leaf senescence score for the first and final assessments of flag leaf senescence respectively.<td style=text-align:center>0
             <td style=text-align:center>9<td>0-9<td>Rating 0-9
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=leaf chlorophyll content'>leaf chlorophyll content</a><td><a href='http://browser.planteome.org/amigo/term/TO:0000495' target='_new'>TO:0000495</a><td>Chlorophyll content of a non-flag leaf<td style=text-align:center>0
             <td style=text-align:center>100<td>spad<td>
             </tr><tr><th>Quality<th>Ontology<th>Description<th>Min<th>Max<th>Unit<th>Unit info<tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=As'>As</a><td><td>Arsenic concentration in grain on a dry weight basis.<td style=text-align:center>0
             <td style=text-align:center>1<td>ppm<td>Parts per million
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=baking quality rating'>baking quality rating</a><td><td>The baking quality of a genotype relative to the standard variety used for that nursery; A= 1, B= 2, C= 3, D= 4, E= 5, F= 6.<td style=text-align:center>1
             <td style=text-align:center>6<td>1-6<td>Rating 1-6
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=baking quality score'>baking quality score</a><td><td>Combined cookie diameter and sucrose SRC relative to a check variety.<td style=text-align:center>0
             <td style=text-align:center>90<td>%<td>Percent
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=Ca'>Ca</a><td><td>Calcium concentration in grain on a dry weight basis.<td style=text-align:center>0
             <td style=text-align:center>1000<td>ppm<td>Parts per million
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=Cd'>Cd</a><td><a href='http://browser.planteome.org/amigo/term/TO:0006059' target='_new'>TO:0006059</a><td>Cadmium concentration on a dry weight basis.<td style=text-align:center>0
             <td style=text-align:center>1.5<td>ppm<td>Parts per million
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=Co'>Co</a><td><td>Cobalt concentration in grain on a dry weight basis.<td style=text-align:center>0
             <td style=text-align:center>10<td>ppm<td>Parts per million
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=cookie diameter'>cookie diameter</a><td><td>Diameter of sugar snap cookie. Reflects genetic and environmental factors. Cookie diameters should be compared to those of standard cultivars.<td style=text-align:center>10
             <td style=text-align:center>20<td>cm<td>Centimeter
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=cookie diameter rating'>cookie diameter rating</a><td><td>Standard deviations from the mean cookie diameter of check varieties; questionable= -1, above average= 1.<td style=text-align:center>-1
             <td style=text-align:center>1<td>standard deviations<td>Standard deviations
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=Cu'>Cu</a><td><td>Copper concentration on a dry weight basis.<td style=text-align:center>0
             <td style=text-align:center>25<td>ppm<td>Parts per million
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=Fe'>Fe</a><td><td>Iron concentration on a dry weight basis.<td style=text-align:center>0
             <td style=text-align:center>100<td>ppm<td>Parts per million
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=flour protein content'>flour protein content</a><td><a href='http://www.cropontology.org/terms/CO_321:0000067/' target='_new'>CO_321:0000067</a><td>Total protein content in refined flour.<td style=text-align:center>0
             <td style=text-align:center>20<td>%<td>Percent
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=flour yield rating'>flour yield rating</a><td><a href='http://www.cropontology.org/terms/CO_321:0000068/' target='_new'>CO_321:0000068</a><td>Standard deviations from the mean flour yield of check varieties; Questionable= -1, above average= 1.<td style=text-align:center>-1
             <td style=text-align:center>1<td>standard deviations<td>Standard deviations
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=flour yield score'>flour yield score</a><td><a href='http://www.cropontology.org/terms/CO_321:0000068/' target='_new'>CO_321:0000068</a><td>Proportion of flour recovered during milling; calculated as (grain weight - bran weight) / grain weight, multiplied by 100.<td style=text-align:center>20
             <td style=text-align:center>90<td>%<td>Percent
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=forage ash'>forage ash</a><td><a href='http://browser.planteome.org/amigo/term/TO:0000207' target='_new'>TO:0000207</a><td>Ash concentration of forage, dwb.  Measured by NIR.<td style=text-align:center>0
             <td style=text-align:center>100<td>%<td>Percent
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=forage fiber'>forage fiber</a><td><a href='http://browser.planteome.org/amigo/term/TO:0000396' target='_new'>TO:0000396</a><td>Fiber concentration of forage, dwb.  Measured by NIR.<td style=text-align:center>0
             <td style=text-align:center>100<td>%<td>Percent
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=forage moisture'>forage moisture</a><td><td>moisture in a forage sample<td style=text-align:center>5
             <td style=text-align:center>25<td>%<td>Percent
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=forage NDF'>forage NDF</a><td><td>Neutral detergent fiber concentration of forage, dwb.  Measured by NIR.<td style=text-align:center>0
             <td style=text-align:center>100<td>%<td>Percent
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=forage protein'>forage protein</a><td><td>Protein concentration of forage, dwb.  Measured by NIR.<td style=text-align:center>0
             <td style=text-align:center>100<td>%<td>Percent
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=forage starch'>forage starch</a><td><td>Starch concentration of forage, dwb.  Measured by NIR.<td style=text-align:center>0
             <td style=text-align:center>100<td>%<td>Percent
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=grain hardness'>grain hardness</a><td><a href='http://www.cropontology.org/terms/CO_321:0000072/' target='_new'>CO_321:0000072</a><td>Grain hardness analysis using the single kernel characterization system 4100 (SKCS, Perten Instruments, Huddinge, Sweden).<td style=text-align:center>0
             <td style=text-align:center>150<td>skcs<td>
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=K'>K</a><td><td>Potassium concentration in grain on a dry weight basis.<td style=text-align:center>0
             <td style=text-align:center>10000<td>ppm<td>Parts per million
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=lactic acid SRC rating'>lactic acid SRC rating</a><td><td>Lactic acid solvent retention capacity (SRC) rated as the standard deviations from the mean lactic acid SRC of check varieties; Questionable= -1, above average= 1.<td style=text-align:center>-1
             <td style=text-align:center>1<td>standard deviations<td>Standard deviations
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=lactic acid SRC score'>lactic acid SRC score</a><td><td>Measure of gluten strength. Typical values are below 85% for weak soft varieties, and above 105% or 110% for strong soft varieties.<td style=text-align:center>60
             <td style=text-align:center>200<td>%<td>Percent
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=Li'>Li</a><td><td>Lithium concentration on a dry weight basis.<td style=text-align:center>0
             <td style=text-align:center>0.2<td>ppm<td>Parts per million
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=lysine content'>lysine content</a><td><a href='http://browser.planteome.org/amigo/term/TO:0002673' target='_new'>TO:0002673</a><td>Lysine in the grain, expressed as percent of protein.<td style=text-align:center>0
             <td style=text-align:center>6<td>%<td>Percent
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=Mg'>Mg</a><td><td>Magnesium concentration in grain on a dry weight basis.<td style=text-align:center>0
             <td style=text-align:center>10000<td>ppm<td>Parts per million
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=milling quality rating'>milling quality rating</a><td><td>Flour yield of a genotype relative to the standard variety used for that nursery; A= 1, B= 2, C= 3, D= 4, E= 5, F= 6.<td style=text-align:center>1
             <td style=text-align:center>6<td>1-6<td>Rating 1-6
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=milling quality score'>milling quality score</a><td><td>Flour yield adjusted by comparison to a check variety.<td style=text-align:center>0
             <td style=text-align:center>100<td>%<td>Percent
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=mixograph peak time'>mixograph peak time</a><td><td>Mixing time to peak dough development, analyzed with a 10 g Mixograph with flour at 14% moisture<td style=text-align:center>0.5
             <td style=text-align:center>10<td>minute<td>Minute
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=Mn'>Mn</a><td><td>Manganese concentration in grain on a dry weight basis.<td style=text-align:center>0
             <td style=text-align:center>1000<td>ppm<td>Parts per million
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=Mo'>Mo</a><td><td>Molybdenum concentration on a dry weight basis.<td style=text-align:center>0
             <td style=text-align:center>2<td>ppm<td>Parts per million
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=modified softness equivalent rating'>modified softness equivalent rating</a><td><td>Softness equivalent is a flour particle size test that is correlated to break flour yields. Softness equivalent rating of a genotype relative to the standard variety used for that nursery; A= 1, B= 2, C= 3, D= 4, E= 5, F= 6.<td style=text-align:center>1
             <td style=text-align:center>6<td>1-6<td>Rating 1-6
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=modified softness equivalent score'>modified softness equivalent score</a><td><td>Softness equivalent is a flour particle size test that is correlated to break flour yields; score calculated as (grain weight - bran weight) - mids / (grain weight - bran weight). Smaller amounts of mids means smaller particle size, greater break flour, greater SE. Adjusted to 15% moisture.<td style=text-align:center>0
             <td style=text-align:center>90<td>%<td>Percent
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=Ni'>Ni</a><td><td>Nickel concentration on a dry weight basis.<td style=text-align:center>0
             <td style=text-align:center>2<td>ppm<td>Parts per million
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=P'>P</a><td><td>Phosphorus concentration in grain on a dry weight basis.<td style=text-align:center>0
             <td style=text-align:center>10000<td>ppm<td>Parts per million
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=Pb'>Pb</a><td><td>ppm lead in a sample<td style=text-align:center>-5
             <td style=text-align:center>10<td>ppm<td>Parts per million
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=Polyphenol oxidase activity'>Polyphenol oxidase activity</a><td><td>Measures oxidation of an L-DOPA substrate to a red-colored product as an indirect measure of PPO activity<td style=text-align:center>0
             <td style=text-align:center>1<td>Absorbance units<td>to be described in trial annotation
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=S'>S</a><td><td>Sulfur concentration in grain on a dry weight basis.<td style=text-align:center>0
             <td style=text-align:center>10000<td>ppm<td>Parts per million
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=SDS sedimentation'>SDS sedimentation</a><td><a href='http://www.cropontology.org/terms/CO_321:0000386/' target='_new'>CO_321:0000386</a><td>Sodium dodecyl sulfate (SDS) sedimentation test for end-use quality.<td style=text-align:center>0
             <td style=text-align:center>0<td>N/A<td>
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=softness equivalent rating'>softness equivalent rating</a><td><td>Softness equivalent is a flour particle size test that is correlated to break flour yields. Rated as the standard deviations from the mean softness equivalent of check varieties; Questionable= -1, above average= 1.<td style=text-align:center>-1
             <td style=text-align:center>1<td>standard deviations<td>Standard deviations
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=softness equivalent score'>softness equivalent score</a><td><td>Softness equivalent is a flour particle size test that is correlated to break flour yields; score calculated as (grain weight - bran weight) - mids / (grain weight - bran weight). Smaller amounts of mids means smaller particle size, greater break flour, greater SE. Not adjusted to standard moisture.<td style=text-align:center>20
             <td style=text-align:center>90<td>%<td>Percent
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=sucrose SRC rating'>sucrose SRC rating</a><td><td>Sucrose solvent retention capacity (SRC) is the best predictor of cookie quality. Rated as the standard deviations from the mean sucrose SRC of check varieties; Questionable= -1, above average= 1.<td style=text-align:center>-1
             <td style=text-align:center>1<td>standard deviations<td>Standard deviations
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=sucrose SRC score'>sucrose SRC score</a><td><td>Sucrose solvent retention capacity (SRC) is the best predictor of cookie quality; sugar snap cookie diameters decrease by 0.07 cm for each percentage point increase in sucrose SRC score.<td style=text-align:center>0
             <td style=text-align:center>200<td>%<td>Percent
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=test weight'>test weight</a><td><a href='http://browser.planteome.org/amigo/term/TO:0000612' target='_new'>TO:0000612</a><td>Density or weight per unit volume of grain at a standard moisture level, typically measured using a Seedboro instrument.<td style=text-align:center>0
             <td style=text-align:center>1000<td>g L-1<td>Grams per liter
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=vegetative protein at maturity'>vegetative protein at maturity</a><td><td>Protein concentration of vegetative biomass harvested at physiological maturity<td style=text-align:center>0
             <td style=text-align:center>100<td>%<td>Percent
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=whole grain ash'>whole grain ash</a><td><td>Grain ash concentration determined by NIR infrared transmittance at 12% moisture<td style=text-align:center>0
             <td style=text-align:center>5<td>%<td>Percent
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=whole grain protein'>whole grain protein</a><td><a href='http://browser.planteome.org/amigo/term/TO:0000598' target='_new'>TO:0000598</a><td>Grain protein determined by NIR infrared transmittance at 12% moisture.<td style=text-align:center>0
             <td style=text-align:center>25<td>%<td>Percent
             </tr><tr><td><a href='//triticeaetoolbox.org/wheat/view.php?table=phenotypes&name=Zn'>Zn</a><td><td>Zinc concentration on a dry weight basis.<td style=text-align:center>0
             <td style=text-align:center>100<td>ppm<td>Parts per million
             </tr></table></div></div>